Specify epsilon for the wgridder manually
ska-sa/codex-africanus pull request #230
Opened 2020-11-06 12:46 UTC by landmanbester

There was a bug in wgridder.dirty which caused the gridder to crash if an epsilon other than the default was used. This should now be fixed. I have also changed the default to 1e-5 regardless of whether single or double precision griding is required.

2020-11-06 13:26 UTC, sjperkins requested changes
Looks good, just needs a HISTORY.rst entry.

2020-11-06 15:34 UTC, landmanbester commented
Yes, I still want to add a test or two as well

2020-11-09 16:23 UTC, landmanbester commented
I think it's good to go in now if you have a sec @sjperkins

2020-11-09 16:28 UTC, sjperkins approved these changes

2020-11-09 16:28 UTC, merged

2020-11-09 16:32 UTC, sjperkins commented
Thanks @landmanbester