Merge Shapelets and Zernike Polynomials into Master
ska-sa/codex-africanus pull request #231
Opened 2020-11-25 07:57 UTC by JoshVStaden

- [ ] Tests added / passed

  ```bash
  $ py.test -v -s africanus
  ```

  If the pep8 tests fail, the quickest way to correct
  this is to run `autopep8` and then `flake8` and
  `pycodestyle` to fix the remaining issues.

  ```
  $ pip install -U autopep8 flake8 pycodestyle
  $ autopep8 -r -i africanus
  $ flake8 africanus
  $ pycodestyle africanus
  ```

- [ ] Fully documented, including `HISTORY.rst` for all changes
      and one of the `docs/*-api.rst` files for new API

  To build the docs locally:

  ```
  pip install -r requirements.readthedocs.txt
  cd docs
  READTHEDOCS=True make html
  ```

2020-11-25 08:04 UTC, JoshVStaden commented
@sjperkins Hi Simon. I have created the PR for this branch. I have removed the dependency of that shapelets package and lowered the amount of test data in the shapelets test. It also seemed that using the SciPy fft in the test cases caused some issues, so I changed them to use the NumPy fft, and it worked without problems. It seems that particular test file takes about 2 seconds to run, and the other test files take about a minute to run. Is this an okay amount, or should this be lowered? 

All that is left now is to just host the binary data for the Zernike beam onto PackRATT. I want to carry on with making the benchmark for the thesis, and then I will get onto that. On that note, I am having issues with specifying the number of CPU cores for Eidos to run on. As far as I can tell, there is no command included in Eidos for this. It seems that Eidos just uses the usual NumPy functions to do multithreading. I have tried searching for a way to force NumPy to use a specific number of cores, but I cannot find this anywhere. Is there something that I could use to do this?

2020-11-25 08:33 UTC, landmanbester commented
Weird. I don't see the option but I remember seeing some multi-processing code in there at some point. Maybe it tries to use all available resources. Can you check if multiple threads spin up when you run it?

2020-11-25 08:40 UTC, landmanbester commented
Unless [this](https://github.com/ratt-ru/eidos/blob/master/eidos/parallelize.py) is only used for the decomposition (not reconstruction)

2020-11-26 06:59 UTC, JoshVStaden commented
It seems that the parallelization does get called for the beam reconstruction. For one frequency, Eidos only runs on one core. However, specifying more than one frequency uses the parallelizing code. I assume then that Eidos parallelizes on frequency. I can also see how to specify the number of CPU cores for Eidos to use. So I think that I should generate a beam for 32 frequencies for each implementation and just vary the number of cores used.

2020-11-30 13:09 UTC, sjperkins commented
> @sjperkins Hi Simon. I have created the PR for this branch. I have removed the dependency of that shapelets package and lowered the amount of test data in the shapelets test. It also seemed that using the SciPy fft in the test cases caused some issues, so I changed them to use the NumPy fft, and it worked without problems. It seems that particular test file takes about 2 seconds to run, and the other test files take about a minute to run. Is this an okay amount, or should this be lowered?

@JoshVStaden Are you saying the final reduced test is 2 seconds (this is great) compared to the original run of about a minute? If so that is fine. If there's a test that still takes a minute, it will need to be further reduced.
 
> All that is left now is to just host the binary data for the Zernike beam onto PackRATT.

So this can simply be a binary .tar.gz. Could you please 

1. Host this on google drive or elwood's FTP
2. Define a registry entry for packratt (as specified [here](https://github.com/ratt-ru/packratt#registry-schemas).
3. Place the registry entry in ``$HOME/.config/packratt/registry.yaml`` and test that it works with your test case.
4. Modify your test case to use packratt to get the file and use the contents?

Once that works, we can host the test data in a more permanent location.

2021-01-29 07:02 UTC, JoshVStaden commented
@sjperkins Hi Simon. I have passed the flake8 tests. It seems that the CI server is only reporting a single error now, This seems to be coming from africanus/rime/tests/test_wsclean_predict.py::test_dask_wsclean_predict. Apparently, when calling dask_wsclean_predict, the test script uses the wrong number of parameters (9 instead of 7). I tried a quick fix for this on my local files to no avail. Once it ran the code, a lot of Numba errors appeared due to unsupported operations. 

I don't want to fiddle too much on code that I haven't created myself, so I was wondering if this is something that can be handled your side?

2021-01-29 08:33 UTC, sjperkins commented
Hi @JoshVStaden https://github.com/ska-sa/codex-africanus/pull/231/commits/d7283904d36b40c24923a0cdec391c388b5cf69c appears to have applied black formatting over the entire code base. I believe, from the Tuesday meeting, that the idea was to apply black formatting to the zernike polynomial code only. Could you please revert and fix?

2021-01-29 12:59 UTC, JoshVStaden commented
@sjperkins I have reverted the changes and applied black formatting on my own code. The issue with dask_wsclean_predict seems to be persisting.

2021-01-29 13:43 UTC, sjperkins commented
@JoshVStaden I'm not seeing the revert of https://github.com/ska-sa/codex-africanus/commit/d7283904d36b40c24923a0cdec391c388b5cf69c. For instance, if one examines the "Files Changed" tab, the averaging code contains formatting changes. Could you please check again?

2021-02-01 10:52 UTC, JoshVStaden commented
@sjperkins Hi Simon. It seems that the code wasn't correctly reverted before. I have reverted it now. The tests are also passing.

2021-02-01 11:46 UTC, sjperkins requested changes
There's still a lot of unnecessary changes @JoshVStaden. Most importantly, this PR currently reverts changes that were recently introduced into master. These must be re-reverted.

This PR  should only contain additions/changes to the zernike/shapelets functionaliy.

2021-02-01 11:46 UTC, sjperkins commented on .gitignore
>  # Distribution / packaging
Revert this whitespace

2021-02-01 11:46 UTC, sjperkins commented on africanus/__init__.py
> +__version__ = '0.2.8'
Revert this version change

2021-02-01 11:46 UTC, sjperkins commented on africanus/averaging/tests/test_mapping.py
> +    )  # noqa
Revert this formatting change

2021-02-01 11:46 UTC, sjperkins commented on africanus/averaging/tests/test_support.py
> +    )  # noqa
Revert this formatting change

2021-02-01 11:46 UTC, sjperkins commented on africanus/averaging/tests/test_time_and_channel_averaging.py
> +    )  # noqa
Revert this formatting change

2021-02-01 11:46 UTC, sjperkins commented on africanus/gridding/wgridder/dask.py
> -from africanus.gridding.wgridder.hessian import HESSIAN_DOCS
Revert removal of hessian code throughout this file

2021-02-01 11:46 UTC, sjperkins commented on africanus/gridding/wgridder/im2residim.py
> -                       do_wstacking, double_accum):
Revert removal of hessian code throughout this file

2021-02-01 11:46 UTC, sjperkins commented on africanus/gridding/wgridder/tests/test_wgridder.py
> -@pmp("nx", (128, ))
Revert removal of hessian code throughout this file

2021-02-01 11:46 UTC, sjperkins commented on africanus/gridding/wgridder/vis2im.py
> -                    do_wstacking, double_accum):
Revert removal of hessian code throughout this file

2021-02-01 11:46 UTC, sjperkins commented on africanus/model/spi/dask.py
>  def _fit_spi_components_wrapper(data, weights, freqs, freq0,
Revert removal of SPI beam code throughout this file

2021-02-01 11:46 UTC, sjperkins commented on africanus/model/spi/tests/test_component_spi.py
> -        def fit_func(nu, I0, alpha): return spi_func(nu, I0, alpha,
Revert removal of beam SPI code throughout this file

2021-02-01 11:46 UTC, sjperkins commented on africanus/rime/cuda/test_shuffle.py
> -            {{var_name}}[{{case}}] = __shfl_sync(mask, {{var_name}}[{{case}}], addr, {{var_length}});
Revert whitespace changes throughout this file

2021-02-01 11:46 UTC, sjperkins commented on africanus/rime/dask.py
> -from africanus.rime.phase import (phase_delay as np_phase_delay,
Revert formatting changes throughout this file

2021-02-01 11:46 UTC, sjperkins commented on africanus/rime/examples/predict.py
> +            print(name, einsum_schema)
Remove print statement

2021-02-01 11:46 UTC, sjperkins commented on africanus/rime/examples/predict.py
> -    p.add_argument("-l", "--l-axis", default="L")
Revert removal of code in this file. (Addition of l and m axis)

2021-02-01 11:46 UTC, sjperkins commented on africanus/rime/examples/predict.py
> -    (l_ax, l_grid), (m_ax, m_grid), (nu_ax, nu_grid) = beam_grids(header,
Revert removal of l_axis and m_axis code in this file

2021-02-01 11:46 UTC, sjperkins commented on africanus/rime/examples/predict.py
> -            spi = [[spectrum.spi]*4]
Revert

2021-02-01 11:46 UTC, sjperkins commented on africanus/rime/examples/predict.py
> -            spi = [[0, 0, 0, 0]]
Revert

2021-02-01 11:46 UTC, sjperkins commented on africanus/rime/examples/predict.py
> -    beam, lm_ext, freq_map = load_beams(args.beam, corr_type,
Revert

2021-02-01 11:46 UTC, sjperkins commented on africanus/rime/examples/predict.py
> +    phase = phase_delay(lm*np.array([[0, 0]]) + np.array([[0, 0.000]]),
This looks incorrect as it zeros all the lm coordinates... Revert

2021-02-01 11:46 UTC, sjperkins commented on setup.py
> +    'ducc0': ['ducc0 >= 0.6.0'],
Revert reversion of ducc0 from 0.8.0 to 0.6.0

2021-02-01 11:46 UTC, sjperkins commented on setup.py
> +    version='0.2.8',
Revert reversion of codex-africanus version from 0.2.9 to 0.2.8

2021-02-01 14:50 UTC, JoshVStaden commented
@sjperkins I have done the necessary changes.

2021-02-01 15:29 UTC, sjperkins requested changes
Looks good, except for 3 version corrections: I think there was some confusion around the phrasing of reverting the reversions.

2021-02-01 15:29 UTC, sjperkins commented on setup.py
> +    version='0.2.8',
Apologies this was a mistake on my part the correct change is 

```suggestion
    version='0.2.9',
```

2021-02-01 15:29 UTC, sjperkins commented on setup.py
> +    'ducc0': ['ducc0 >= 0.6.0'],
I think the double-negative was  confusing here:

```suggestion
    'ducc0': ['ducc0 >= 0.8.0'],
```

2021-02-01 15:52 UTC, JoshVStaden commented
@sjperkins I changed the version numbers back

2021-02-01 16:12 UTC, sjperkins approved these changes

2021-02-01 16:13 UTC, merged

2021-02-01 16:30 UTC, o-smirnov commented
Yay!